const hymnsData = {

   "1. HOLY HOLY HOLY":"Mungu mutakatifu (Nyimbo za Mungu 5)\nBy Reginald Heber (1826)\n\n1. Holy, holy, holy! Lord God Almighty!\nEarly in the morning our song shall rise to Thee;\nHoly, holy, holy, merciful and mighty!\nGod in three Persons, blessed Trinity!\n\n2. Holy, holy, holy! All the saints adore Thee,\nCasting down their golden crowns around the glassy sea;\nCherubim and seraphim falling down before Thee,\nWho was, and is, and evermore shall be.\n\n3. Holy, holy, holy! though the darkness hide Thee,\nThough the eye of sinful man Thy glory may not see;\nOnly Thou art holy; there is none beside Thee,\nPerfect in power, in love, and purity.\n\n4. Holy, holy, holy! Lord God Almighty!\nAll Thy works shall praise Thy Name, in earth, and sky, and sea;\nHoly, holy, holy; merciful and mighty!\n God in three Persons, blessed Trinity!",
"2. OLD RUGGED CROSS":"By George Bennard (1913)\n\n1. On a hill far away\n stood an old rugged cross,\nthe emblem of suffering and shame;\nand I love that old cross\nwhere the dearest and best\nfor a world of lost sinners was slain.\n\nRefrain:\n\nSo I'll cherish the old rugged cross,\ntill my trophies at last I lay down;\nI will cling to the old rugged cross,\nand exchange it some day for a crown.\n\n2. O that old rugged cross,\nso despised by the world,\nhas a wondrous attraction for me:\nfor the dear Lamb of God\nleft his glory above\nto bear it to dark Calvary.\n\n3. In that old rugged cross,\nstained with blood so divine,\na wondrous beauty I see,\nfor 'twas on that old cross\nJesus suffered and died,\nto pardon and sanctify me.\n\n4. To that old rugged cross\nI will ever be true,\nits shame and reproach gladly bear;\nthen he'll call me some day\nto my home far away,\nwhere his glory forever I'll share.",
"3. ALL TO JESUS I SURRENDER": "Entre tes mains j'abandonne\nBy Judson W. Van De Venter (1896)\n\n1. All to Jesus, I surrender;\nAll to Him I freely give;\nI will ever love and trust Him,\nIn His presence daily live.\n\nRefrain:\n\nI surrender all, I surrender all,\nAll to Thee, my blessed Savior,\nI surrender all.\n\n2. All to Jesus I surrender;\nHumbly at His feet I bow,\nWorldly pleasures all forsaken;\nTake me, Jesus, take me now\n\n3. All to Jesus, I surrender;\nMake me, Savior, wholly Thine;\nLet me feel the Holy Spirit,\nTruly know that Thou art mine.\n\n4. All to Jesus, I surrender:\nLord, I give myself to Thee;\nFill me with Thy love and power;\nLet Thy blessing fall on me.",
"4. TRUST AND OBEY": "Tukikwenda pamoja (Nyimbo za Mungu 162)\nBy John H. Sammis (1887)\n\n1. When we walk with the Lord\nin the light of his word,\nwhat a glory he sheds on our way!\nWhile we do his good will,\nhe abides with us still,\nand with all who will trust and obey.\n\nRefrain:\n\nTrust and obey, for there's no other way\nto be happy in Jesus, but to trust and obey.\n\n2. Not a burden we bear,\nnot a sorrow we share,\nbut our toil he doth richly repay;\nnot a grief or a loss,\nnot a frown or a cross,\nbut is blest if we trust and obey.\n\n3. But we never can prove\nthe delights of his love\nuntil all on the altar we lay;\nfor the favor he shows,\n for the joy he bestows,\nare for them who will trust and obey.\n\n4. Then in fellowship sweet\nwe will sit at his feet,\nor we'll walk by his side in the way;\nwhat he says we will do,\nwhere he sends we will go;\nnever fear, only trust and obey.", 
"5. WHAT A FRIEND":"Yesu ni rafiki yangu (Nyimbo za Mungu 235)\nBy Joseph Medlicott Scriven (1855)\n\n1. What a friend we have in Jesus,\nall our sins and griefs to bear!\nWhat a privilege to carry\neverything to God in prayer!\nO what peace we often forfeit,\nO what needless pain we bear,\nall because we do not carry\neverything to God in prayer!\n\n2. Have we trials and temptations?\nIs there trouble anywhere?\nWe should never be discouraged;\ntake it to the Lord in prayer!\nCan we find a friend so faithful\nwho will all our sorrows share?\nJesus knows our every weakness;\ntake it to the Lord in prayer!\n\n3. Are we weak and heavy laden,\ncumbered with a load of care?\nPrecious Savior, still our refuge\ntake it to the Lord in prayer!\nDo your friends despise, forsake you?\nTake it to the Lord in prayer!\nIn his arms he'll take and shield you;\nyou will find a solace there.",
"6. WHAT CAN WASH AWAY":"Nini ita nisafisha (Nyimbo za Mungu 113)\nBy Robert Lowry (1876)\n\n1. What can wash away my sin?\nNothing but the blood of Jesus;\nWhat can make me whole again?\nNothing but the blood of Jesus.\n\nRefrain:\n\nOh! precious is the flow\nThat makes me white as snow;\nNo other fount I know,\nNothing but the blood of Jesus.\n\n2. For my pardon, this I see,\nNothing but the blood of Jesus;\nFor my cleansing this my plea,\nNothing but the blood of Jesus.\n\n3. Nothing can for sin atone,\nNothing but the blood of Jesus;\nNaught of good that I have done,\nNothing but the blood of Jesus.\n\n4. This is all my hope and peace,\nNothing but the blood of Jesus;\nThis is all my righteousness,\nNothing but the blood of Jesus.",
"7. AMAZING GRACE":"By John Newton (1779)\n\n1. Amazing grace (how sweet the sound)\nthat saved a wretch like me!\nI once was lost, but now am found,\nwas blind, but now I see.\n\n2. 'Twas grace that taught my heart to fear,\nand grace my fears relieved;\nhow precious did that grace appear\nthe hour I first believed!\n\n3. Through many dangers, toils and snares\nI have already come;\n'tis grace has brought me safe thus far,\nand grace will lead me home.\n\n4. The Lord has promised good to me,\nhis word my hope secures;\nhe will my shield and portion be\nas long as life endures.\n\n5. Yes, when this flesh and heart shall fail,\nand mortal life shall cease\nI shall possess, within the veil,\na life of joy and peace.\n\n6. The earth shall soon dissolve like snow,\nthe sun forbear to shine;\nbut God, who called me here below,\nwill be forever mine.",
"8. AS THE DEER PATHETH":"By Greg Scheer\n\n1. As the deer panteth for the water\nSo my soul longeth after thee\nYou alone are my heart's desire\nAnd I long to worship thee\n\n2. You alone are my strength, my shield\nTo you alone may my spirit yield\nYou alone are my heart's desire\nAnd I long to worship thee\n\n3. You're my friend and you are my brother\nEven though you are a king\nI love you more than any other\nSo much more than anything\n\n4. You alone are my strength, my shield\nTo you alone may my spirit yield\nYou alone are my heart's desire\nAnd I long to worship thee.\n\n5. I love you more than gold or silver,\nOnly you can satisfy.\nYou alone are the real joy giver\nAnd the apple of my eye.\n\n6. You alone are my strength, my shield\nTo you alone may my spirit yield\nYou alone are my heart's desire\nAnd I long to worship you.",
"9. BLESSED ASSURANCE": "Heri Kabisa Yesu ni wangu (Nyimbo za Mungu 138)\nBy Fanny Crosby\n\n1. Blessed assurance, Jesus is mine!\nO what a foretaste of glory divine!\nHeir of salvation, purchase of God,\n Born of his Spirit, washed in his blood.\n\nRefrain:\n\nThis is my story, this is my song,\nPraising my Savior, all the day long;\nThis is my story, this is my song,\nPraising my Savior all the day long.\n\n2. Perfect submission, perfect delight,\nVisions of rapture now burst on my sight;\nAngels descending, bring from above\nEchoes of mercy, whispers of love.\n\n3. Perfect submission, all is at rest,\nI in my Savior am happy and blest,\nWatching and waiting, looking above,\nFilled with his goodness, lost in his love.",
"10. COUNT YOUR BLESSINGS":"Ukichukuliwa na mashaka (Nyimbo za Mungu 189)\nBy Johnson Oatman (1897)\n\n1. When upon life's billows you are tempest tossed,\nWhen you are discouraged, thinking all is lost,\nCount your many blessings, name them one by one,\nAnd it will surprise you what the Lord hath done.\n\nRefrain:\n\nCount your blessings, name them one by one;\nCount your blessings, see what God hath done;\nCount your blessings, name them one by one;\nCount your many blessings, see what God hath done.\n\n2. Are you ever burdened with a load of care?\nDoes the cross seem heavy you are called to bear?\nCount your many blessings, ev'ry doubt will fly,\nAnd you will be singing as the days go by.\n\n3. When you look at others with their lands and gold,\nThink that Christ has promised you His wealth untold;\nCount your many blessings, money cannot buy\nYour reward in heaven, nor your home on high.\n\n4. So, amid the conflict, whether great or small,\nDo not be discouraged, God is over all;\nCount your many blessings, angels will attend,\nHelp and comfort give you to your journey's end.",
"11. GIVE THANKS": "By Henry Smith\n\nGive thanks with a grateful heart\nGive thanks to the Holy One\nGive thanks because He's given\nJesus Christ, His Son. (repeat)\n\nAnd now let the weak say, 'I am strong'\nLet the poor say, 'I am rich'\nBecause of what the Lord has done for us (2)",
"12. HOW GREAT THOU ART":"Nina fikili Mungu Baba (Nyimbo za Mungu 11)\nBy Carl Gustav Boberg\n\n1. Oh Lord my God when I in awesome wonder\nConsider all the works Thy hands have made,\nI see the stars, I hear the rolling thunder,\nThy power throughout the universe displayed.\n\nRefrain:\n\nThen sings my soul, my Savior God, to thee:\nHow great Thou art, how great Thou art! (2)\n\n2. When through the woods and forest glades I wander,\nAnd hear the birds sing sweetly in the trees;\nWhen I look down from lofty mountain grandeur,\nAnd hear the brook, and feel the gentle breeze.\n\n3. And when I think that God, His Son not sparing,\nSent Him to die, I scarce can take it in;\nThat on the cross, my burden gladly bearing,\nHe bled and died to take away my sin.\n\n4. When Christ shall come with shouts of acclamation\nAnd take me home, what joy shall fill my heart!\nThen I shall bow in humble adoration\nAnd there proclaim, my God, how great Thou art!",
"13. THERE IS POWER IN THE BLOOD":"Utakubali kuacha makosa (Nyimbo za Mungu 112)\nBy Lewis E. Jones (1899)\n\n1. Would you be free from the burden of sin?\nThere's power in the blood, power in the blood;\nWould you o'er evil a victory win?\nThere's wonderful power in the blood.\n\nChorus:\n\nThere is power, power, wonder-working power\nIn the blood of the Lamb.\nThere is power, power, Wonder-working power\nIn the precious blood of the Lamb.\n\n2. Would you be free from your passion and pride?\nThere's power in the blood, power in the blood;\nCome for a cleansing to Calvary's tide;\nThere's wonderful power in the blood.\n\n3. Would you be whiter, much whiter than snow?\nThere's power in the blood, power in the blood;\nSin stains are lost in its life-giving flow;\nThere's wonderful power in the blood.\n\n4. Would you do service for Jesus your King?\nThere's power in the blood, power in the blood;\nWould you live daily His praises to sing?\nThere's wonderful power in the blood.",
"14. ROCK OF AGES": "Mwamba ulio pasuka (Nyimbo za Mungu 118)\nBy Augustus Toplady (1776)\n\n1. Rock of Ages, cleft for me,\nLet me hide myself in thee;\nLet the water and the blood,\nFrom thy wounded side which flowed,\nBe of sin the double cure;\nSave from wrath and make me pure.\n\n2. Not the labors of my hands\nCan fulfill thy law's demands;\nCould my zeal no respite know,\nCould my tears forever flow,\nAll for sin could not atone;\nThou must save, and thou alone.\n\n3. Nothing in my hand I bring,\nSimply to the cross I cling;\nNaked, come to thee for dress;\nHelpless, look to thee for grace;\nFoul, I to the fountain fly;\nWash me, Savior, or I die.\n\n4. While I draw this fleeting breath,\nWhen mine eyes shall close in death,\nWhen I soar to worlds unknown,\nSee thee on thy judgment throne,\nRock of Ages, cleft for me,\nLet me hide myself in thee.",
"15. WHEN I SURVEY THE WONDROUS CROSS":"By Isaac Watts (1707)\n\n1. When I survey the wondrous cross\nOn which the Prince of glory died,\nMy richest gain I count but loss,\nAnd pour contempt on all my pride.\n\n2. Forbid it, Lord, that I should boast,\nSave in the death of Christ my God!\nAll the vain things that charm me most,\nI sacrifice them to His blood.\n\n3. See from His head, His hands, His feet,\nSorrow and love flow mingled down!\nDid e'er such love and sorrow meet,\nOr thorns compose so rich a crown?\n\n4. His dying crimson, like a robe,\nSpreads o'er His body on the tree;\nThen I am dead to all the globe,\nAnd all the globe is dead to me.\n\n5. Were the whole realm of nature mine,\nThat were a present far too small;\nLove so amazing, so divine,\nDemands my soul, my life, my all.\n\n6. To Christ, Who won for sinners grace\nBy bitter grief and anguish sore,\nBe praise from all the ransomed race\nForever and forevermore.",
"16. HEAVENLY SUNLIGHT":"By Henry J. Zelley (1899)\n\n1. Walking in sunlight all of my journey,\nOver the mountains, through the deep vale;\nJesus has said, \"I'll never forsake thee\",\nPromise divine that never can fail.\n\nRefrain:\n\nHeavenly sunlight, heavenly sunlight,\nFlooding my soul with glory divine:\nHallelujah, I am rejoicing,\nSinging His praises, Jesus is mine.\n\n2. Shadows around me, shadows above me,\nNever conceal my Savior and Guide:\nHe is the Light, in Him is no darkness;\nEver I'm walking close to His side.\n\n3. In the bright sunlight, ever rejoicing,\nPressing my way to mansions above:\nSinging His praises gladly I'm walking,\nWalking in sunlight, sunlight of love.",
"17. JUST A CLOSER WALK WITH THEE":"By Anonymous\n\n1. I am weak, but Thou art strong;\nJesus, keep me from all wrong;\n I'll be satisfied as long\nas I walk, let me walk close to Thee.\n\nRefrain:\n\nJust a closer walk with Thee,\nGrant it, Jesus, is my plea,\nDaily walking close to Thee,\n\n2. Let it be, dear Lord,\nlet it be Through this world of toil and snares\nIf I falter, Lord, who cares?\nWho with me my burden shares?\nNone but Thee, dear Lord, none but Thee.\n\n3. When my feeble life is o'er,\nTime for me will be no more;\nGuide me gently, safely o'er\nTo Thy ingdom shore, to Thy shore.",
"18. JESUS PAID IT ALL":"Bwana Yesu amesema Ee wewe (Nyimbo za Mungu 84)\nBy Elvina M. HalI\n\n 1. I hear the Savior say,\n \"Thy strength indeed is small;\nChild of weakness, watch and pray,\n find in me thine all in all.\"\n\nRefrain:\n\nJesus paid it all, all to him I owe;\n sin had left a crimson stain,\n he washed it white as snow.\n\n2. Lord, now indeed I find\n thy power, and thine alone\n Can change the leper's spots\n and melt the heart of stone.\n\n3. For nothing good have I\n whereby thy grace to claim;\nI'll wash my garments clean\nin the blood of Calvary's Lamb.\n\n 4. And when, before the throne,\nI stand in him complete,\n\"Jesus died my soul to save,\"\n my lips shall still repeat.\"",
"19. LIKE A RIVER GLORIOUS":"By Frances Ridley Havergal\n\n1. Like a river, glorious\nIs God's perfect peace,\nOver all victorious\nIn its bright increase;\nPerfect, yet it floweth\nFuller every day,\nPerfect, yet it groweth\nDeeper all the way\n\nRefrain:\n\nStayed upon Jehovah,\nHearts are fully blest;\nFinding, as He promised,\nPerfect peace and rest\n\n2. Hidden in the hollow\nOf His blessed hand,\nNever foe can follow,\nNever traitor stand;\nNot a surge of worry,\nNot a shade of care,\nNot a blast of hurry\nTouch the spirit there\n\n3. Every joy or trial\nFalleth from above,\nTraced upon our dial\nBy the Sun of Love.\nWe may trust Him fully\nAll for us to do;\nThey who trust Him wholly\nFind Him wholly true",
"20. PRAISE HIM! PRAISE HIM":"Sifu sifu Yesu mwokozi (Nyimbo za Mungu 4)\nBy Fanny Crosby (1869)\n\n1. Praise him! praise him! Jesus, our blessed Redeemer!\nSing, O earth - his wonderful love proclaim!\nHail him! hail him! highest archangels in glory,\nStrength and honor give to his holy name!\nLike a shepherd, Jesus will guard his children \nIn his arms he carries them all day long:\n\nRefrain:\n\nPraise him! praise him! tell of his excellent greatness!\nPraise him! praise him! ever in joyful song!\n\n2. Praise him! praise him! Jesus, our blessed Redeemer!\nFor our sins he suffered and bled and died;\nHe our Rock, our hope of eternal salvation,\nHail him! hail him! Jesus the Crucified!\nSound his praises - Jesus who bore our sorrows\nLove unbounded, wonderful, deep and strong:\n\n3. Praise him! praise him! Jesus, our blessed Redeemer!\nHeav'nly portals loud with hosannas ring!\nJesus, Savior, reigneth for ever and ever,\nCrown him! crown him! Prophet and Priest and King!\nChrist is coming, over the world victorious \nPow'r and glory unto the Lord belong",
"21. I WILL SING THE WONDROUS STORY":"Nitaimba na kusifu (Nyimbo za Mungu 10)\nBy Francis H. Rowley (1886)\n\n1. I will sing the wondrous story\nof the Christ who died for me,\nhow He left His home in glory\nfor the cross of Calvary.\n\nRefrain:\n\nYes, I'll sing the wondrous story\nOf the Christ who died for me,\nSing it with the saints in glory,\nGathered by the crystal sea.\n\n2. I was lost, but Jesus found me,\nfound the sheep that went astray,\nthrew His loving arms around me,\ndrew me back into His way.\n\n3. I was bruised, but Jesus healed me;\nfaint was I from many a fall;\nsight was gone, and fears possessed me,\nbut He freed me from them all.\n\n4. Days of darkness still come o'er me,\nsorrow's path I often tread,\nbut the Savior still is with me;\nby His hand I'm safely led.",
"22. THE CHURCH'S ONE FOUNDATION":"Musingi wa kanisa ni Kristo (Nyimbo za Mungu 13)\nBy S. J. Stone (1866)\n\n1. The church's one Foundation\nis Jesus Christ her Lord;\nshe is His new creation,\nby water and the Word:\nfrom heav'n He came and sought her\nto be His holy bride;\nwith His own blood He bought her,\nand for her life He died.\n\n2. Elect from ev'ry nation,\nyet one o'er all the earth.\nher charter of salvation,\none Lord, one faith, one birth:\none holy Name she blesses,\npartakes one holy food,\nand to one hope she presses,\nwith ev'ry grace endued.\n\n3. Tho' with a scornful wonder,\nmen see her sore oppressed,\nby schisms rent asunder,\nby heresies distressed,\nyet saints their watch are keeping,\ntheir cry goes up, \"How long?\"\nAnd soon the night of weeping\nshall be the morn of song.\n\n4. The church shall never perish!\nHer dear Lord, to defend,\nto guide, sustain, and cherish,\nis with her to the end;\ntho' there be those that hate her\nand false sons in her pale,\nagainst the foe or traitor\nshe ever shall prevail.\n\n5. 'Mid toil and tribulation,\nand tumult of her war,\nshe waits the consummation\nof peace for evermore;\ntill with the vision glorious\nher longing eyes are blest,\nand the great church victorious\nshall be the church at rest.\n\n6. Yet she on earth hath union\nwith God the Three in One,\nand mystic sweet communion\nwith those whose rest is won.\nO happy ones and holy!\nLord, give us grace that we,\nlike them, the meek and lowly,\non high may dwell with Thee.",
"23. TO GOD BE THE GLORY":"Kwa Mungu mujuu (Nyimbo za Mungu 32)\nBy Fanny Crosby (1875)\n\n1. To God be the glory, great things he hath done\nso loved he the world that he gave us his Son\nwho vielded his life an atonement for sin.\nand opened the life-gate that all may go in.\n\nRefrain:\n\nPraise the Lord, praise the Lord, let the earth hear his voice!\nPraise the Lord, praise the Lord, let the people rejoice!\n O come to the Father through Jesus the Son,\n and give him the glory, great things he hath done.\n\n2. O perfect redemption, the purchase of blood,\nto every believer the promise of God;\nthe vilest offender who truly believes,\nthat moment from Jesus a pardon receives.\n\n3. Great things he hath taught us, great things he hath.done,\nand great our rejoicing through Jesus the Son;\nbut purer, and higher and greater will be\nour wonder, our transport, when Jesus we see.",
"24. REDEEMED":"Nimekombolewa kabisa (Nyimbo za Mungu 98)\nBy Fanny Crosby (1882)\n\n1. Redeemed, how I love to proclaim it!\nRedeemed by the blood of the Lamb;\nredeemed through His infinite mercy,\nHis child, and forever I am.\n\nRefrain:\n\nRedeemed, redeemed,\nredeemed by the blood of the Lamb:\nredeemed, redeemed,\nHis child and forever I am.\n\n2. Redeemed, and so happy in Jesus,\nno language my rapture can tell:\nI know that the light of His presence\nwith me doth continually dwell.\n\n3. I think of my blessed Redeemer,\nI think of Him all the day long;\nI sing, for I cannot be silent;\nHis love is the theme of my song.",
"25. TELL ME THE STORY OF JESUS":"By Fanny Crosby (1880)\n\n1. Tell me the story of Jesus,\nwrite on my heart every word;\ntell me the story most precious,\nSweetest that ever was heard.\nTell how the angels, in chorus,\nsang as they welcomed His birth,\n\"Glory to God in the highest!\nPeace and good tidings to earth.\"\n\nRefrain:\n\nTell me the story of Jesus,\nwrite on my heart every word;\ntell me the story most precious,\nSweetest that ever was heard.\n\n2. Fasting alone in the desert,\ntell of the days that are past;\nhow for our sins He was tempted,\nyet was triumphant at last.\nTell of the years of His labor,\ntell of the sorrow He bore;\nHe was despised and afflicted,\nhomeless, rejected and poor.\n\n3. Tell of the cross where they nailed Him,\nwrithing in anguish and pain;\ntell of the grave where they laid Him,\ntell how He liveth again.\nLove in that story so tender,clearer than ever I see:\nstay, let me weep while you whisper,\nlove paid the ransom for me.",
"26. PRAISE THE LORD, THE ALMIGHTY":"By Joachim Neander (1680)\n\n1. Praise to the Lord, the Almighty, the King of creation!\nO my soul, praise him, for he is your health and salvation!\n Come, all who hear; now to his temple draw near,\n join me in glad adoration.\n\n2. Praise to the Lord, above all things so wondrously reigning;\n sheltering you under his wings, and so gently\n sustaining!\n Have you not seen all that is needful has been\nsent by his gracious ordaining?\n\n3. Praise to the Lord, who will prosper your work and defend you;\n.surely his goodness and mercy shall daily attend you.\nPonder anew what the Almighty can do,\nif with his love he befriends you.\n\n4. Praise to the Lord! O let all that is in me adore him!\nAll that has life and breath, come now with praises\nbefore him.\nLet the Amen sound from his people again;\ngladly forever adore him.",
"27. SILENT NIGHT, HOLY NIGHT":"Kwa usiku wa zamani (Nyimbo za Mungu 284)\nBy Joseph Mohr\n\n1. Silent night! Holy night!\nAll is calm, all is bright\n'round yon virgin mother and child!\nHoly infant, so tender and mild.\nsleep in heavenly peace,\nsleep in heavenly peace.\n\n2. Silent night! Holy night!\nShepherds quake at the sight.\nGlories stream from heaven afar,\nheav'nly hosts sing: \"Alleluia!\n Christ the Savior is born!\nChrist the Savior is born!\"\n\n3. Silent night! Holy night!\nSon of God, love's pure light\nradiant beams from Thy holy face\nwith the dawn of redeeming grace,\nJesus, Lord, at Thy birth!\nJesus, Lord, at Thy birth!\n\n4. Silent night! Holy night!\nWondrous star, lend thy light;\nwith the angels let us sing\n\"Alleluia\" to our King:\n\"Christ the Savior is born!\nChrist the Savior is born.\"",
"28. MAN OF SORROWS":"Mutu wa masikitiko (Nyimbo za Mungu 40)\nBy P. P. Bliss (1875)\n\n1. Man of sorrows what a name\nfor the Son of God, who came\nruined sinners to reclaim:\nHallelujah, what a Savior!\n\n2. Bearing shame and scoffing rude,\nin my place condemned he stood,\nsealed my pardon with his blood:\nHallelujah, what a Savior!\n\n3. Guilty, helpless, lost were we;\nblameless Lamb of God was he.\nsacrificed to set us free:\nHallelujah, what a Savior!\n\n4. He was lifted up to die;\n\"It is finished\" was his cry;\nnow in heaven exalted high:\nHallelujah, what a Savior!\n\n5. When he comes, our glorious King,\nall his ransomed home to bring,\nthen anew this song we'll sing:\nHallelujah, what a Savior!",
"29. AT THE CROSS":"By Isaac Watts (1707)\n\n1. Alas! and did my Savior bleed,\nand did my Sovereign die!\nWould he devote that sacred head\nfor sinners such as I?\n\n2. Was it for crimes that I have done,\nhe groaned upon the tree?\nAmazing pity! Grace unknown!\nAnd love beyond degree!\n\n3. Well might the sun in darkness hide,\nand shut its glories in,\nwhen God, the mighty maker, died\nfor his own creature's sin.\n\n4. Thus might I hide my blushing face\nwhile his dear cross appears;\ndissolve my heart in thankfulness,\nand melt mine eyes to tears.\n\n5. But drops of tears can ne'er repay\nthe debt of love I owe.\nHere, Lord, I give myself away:'tis all that I can do.",
"30. CHRIST THE LORD IS RISEN TODAY":"Yesu amefufuliwa (Nyimbo za Mungu 287)\nBy Charles Wesley (1739)\n\n1. Christ the Lord is risen today, Alleluia!\nEarth and heaven in chorus say, Alleluia!\nRaise your joys and triumphs high, Alleluia!\nSing, ye heavens, and earth reply, Alleluia!\n\n2. Love's redeeming work is done, Alleluia!\nFought the fight, the battle won, Alleluia!\nDeath in vain forbids him rise, Alleluia!\nChrist has opened paradise, Alleluia!\n\n3. Lives again our glorious King, Alleluia!\nWhere, O death, is now thy sting? Alleluia!\nOnce he died our souls to save, Alleluia!\nWhere's thy victory, boasting grave? Alleluia!\n\n4. Soar we now where Christ has led, Alleluia!\nFollowing our exalted Head, Alleluia!\nMade like him, like him we rise, Alleluia!\nOurs the cross, the grave, the skies, Alleluia!\n\n5. Hail the Lord of earth and heaven, Alleluia!\nPraise to thee by both be given, Alleluia!\nThee we greet triumphant now, Alleluia!\nHail the Resurrection, thou, Alleluia!\n\n6. King of glory, soul of bliss, Alleluia!\nEverlasting life is this, Alleluia!\nThee to know, thy power to prove, Alleluia!\nThus to sing, and thus to love, Alleluia!",
"31. WILL JESUS FIND US WATCHING?":"Yesu atakapokuja tena (Nyimbo za Mungu 312)\nBy Frances J. Crosby, 1876\n\n1. When Jesus comes to reward His servants,\nWhether it be noon or night,\nFaithful to Him will He find us watching,\nWith our lamps all trimmed and bright?\n\nRefrain:\n\nOh, can we say we are ready, brother?\nReady for the soul's bright home?\nSay, will He find you and me still watching,\nWaiting, waiting when the Lord shall come?\n\n2. If, at the dawn of the early morning,\nHe shall call us one by one,\nWhen to the Lord we restore our talents,\nWill He answer thee, 'Well done'?\n\n3. Have we been true to the trust He left us?\nDo we seek to do our best?\nIf in our hearts there is naught condemns us,\nWe shall have a glorious rest.\n\n4. Blessed are those whom the Lord finds watching,\nIn His glory they shall share;\nIf He shall come at the dawn or midnight,\nWill He find us watching there?",
"32. HOLY SPIRIT FAITHFUL GUIDE":"Kiongozi mwana wa Mungu (Nyimbo za Mungu 238/185)\nBy M. M. Wells\n\n1. Holy Spirit, faithful Guide,\nEver near the Christian's side;\nGently lead us by the hand,\nPilgrims in a desert land;\nWeary souls fore'er rejoice,\nWhile they hear that sweetest voice,\nWhisp'ring softly, 'Wand'rer, come!\nFollow Me, I'll guide thee home.\n\n2. Ever present, truest Friend,\nEver near Thine aid to lend,\nLeave us not to doubt and fear.\nGroping on in darkness drear;\nWhen the storms are raging sore,\nHearts grow faint, and hopes give o'er.\nWhisp'ring softly, 'Wand'rer, come!\nFollow Me, I'll guide thee home.\n\n3. When our days of toil shall cease,\nWaiting still for sweet release,\nNothing left but heav'n and prayer,\nWond'ring if our names were there;\nWading deep the dismal flood,\nPleading naught but Jesus' blood,\nWhisp'ring softly, 'Wand'rer, come!\nFollow Me, I'll guide thee home.",
"33. O SPREAD THE TIDINGS' ROUND":"Tangaza neno hili dunia isikie (Nyimbo za Mungu 122)\nBy Francis Bottome\n\n1. O spread the tidings 'round, wherever man is found,\nWherever human hearts and human woes abound.\nLet every Christian tongue proclaim the joyful sound:\nThe Comforter has come!\n\nRefrain:\nThe Comforter has come! The Comforter has come!\nThe Holy Ghost from heav'n, the Father's promise giv'n,\nO spread the tidings 'round, wherever man is found:\nThe Comforter has come!\n\n2. The long, long night is past; the morning breaks at last;\nAnd hushed the dreadful wail and fury of the blast,\nAs o'er the golden hills the day advances fast!\nThe Comforter has come!\n\n3. Lo, the great King of kings, with healing in His wings,\nTo every captive soul a full deliverance brings;\nAnd thro' the vacant cells the song of triumph rings;\nThe Comforter has come!\n\n4. O boundless love divine! How shall this tongue of mine\nTo wond'ring mortals tell the matchless grace divine\nThat I, a child of hell, should in His image shine?\nThe Comforter has come!",
"34. SAFELY THROUGH ANOTHER WEEK":"34. Hata juma hili Bwana (Nyimbo za Mungu 21)\nBy Isaac Newton 1774\n\n1. Safely through another week\n God has brought us on our way;\nlet us now a blessing seek,\nwaiting in His courts today;\nday of all the week the best,\n emblem of eternal rest.\n\n2. While we pray for pard'ning grace,\n through the dear Redeemer's name,\nshow Thy reconciling face;\n take away our sin and shame;\n from our worldly cares set free,\nmay we rest this day in Thee.\n\n3. Here we come Thy name to praise,\n let us feel Thy presence near;\n may Thy glory meet our eyes,\n while we in Thy house appear:\n here afford us, Lord, a taste\nof our everlasting feast.\n\n 4. May Thy gospel's joyful sound\n conquer sinners, comfort saints;\n may the fruits of grace abound,\n bring relief for all complaints:\n thus may all our Sabbaths prove,\n till we join the church above.",
"35. BREAK THOUGH THE BREAD OF LIFE": "Mukate wa Uzima (Nyimbo za Mungu 189/236)\nBy Miss Mary A. Lathbury, 1877\n\nthe bread of life, dear Lord, to me,\n 1. Break now the\n as once you broke the loaves beside the sea.\nBeyond the sacred page I seek you, Lord:\n my spirit waits for you, O living Word.\n\n 2. Bless your own word of truth, dear Lord, to me,\n as when you blessed the bread by Galilee.\n Then shall all bondage cease, all fetters fall;\n and I shall find my peace, my All in all!\n\n 3. You are the bread of life, dear Lord, to me,\n your holy word the truth that rescues me.\n Give me to eat and live with you above;\n teach me to love your truth, for you are love.\n\n 4. O send your Spirit now, dear Lord, to me,\n that he may touch my eyes and make me see.\n Show me the truth made plain within your Word,\n for in your book revealed I see you, Lord.",
"36. ABIDE WITH ME":"Ukae nami giza lina fika (Nyimbo za Mungu 298/245)\nBy Henry Francis Lyte (1847)\n\n 1. Abide with me: fast falls the eventide;\n the darkness deepens; Lord, with me abide.\nWhen other helpers fail and comforts flee,\nHelp of the helpless, O abide with me.\n\n 2. Swift to its close ebbs out life's little day;\n earth's joys grow dim, its glories pass away.\n Change and decay in all around I see.\n O Lord who changes not, abide with me.\n\n3. I need your presence every passing hour.\n What but your grace can foil the tempter's power?\n Who like yourself my guide and strength can be?\nThrough cloud and sunshine, O abide with me.\n\n4. I fear no foe with you at hand to bless,\nthough ills have weight, and tears their bitterness\n Where is death's sting? Where, grave, your victory?\n I triumph still, if you abide with me.\n\n5. Hold now your Word before my closing eyes.\nShine through the gloom and point me to the skies.\n Heaven's morning breakS and earth's vain shadows flee;\nin life, in death, O Lord, abide with me.",
"37. STANDING ON THE PROMISES":"Usimame kwa ahadi zake (Nyimbo za Mungu 194/141)\nBy Russell Kelso Carter (1886)\n\n1. Standing on the promises of Christ my king,\nThrough eternal ages let His praises ring;\nGlory in the highest, I will shout and sing,\nStanding on the promises of God.\n\nRefrain:\n\nStanding, standing,\nStanding on the promises of God my Savior;\nStanding, standing,\nI'm standing on the promises of God.\n\n 2. Standing on the promises that cannot fail,\nWhen the howling storms of doubt and fear assail,\nBy the living Word of God I shall prevail,\nStanding on the promises of God.\n\n3. Standing on the promises of Christ the Lord,\nBound to Him eternally by love's strong cord,\nOvercoming daily with the Spirit's sword,\nStanding on the promises of God.\n\n4. Standing on the promises I cannot fall,\nListening every moment to the Spirit's call,\nResting in my Savior as my all in all,\nStanding on the promises of God.",
"38. BLESSED BE THE TIE THAT BINDS":"By John Fawcett (1782)\n\n1. Blest be the tie that binds\nOur hearts in Christian love;\nThe fellowship of kindred minds\nIs like to that above.\n\n2. Before our Father's throne\nWe pour our ardent prayers;\nOur fears, our hopes, our aims are one,\nOur comforts and our cares.\n\n3. We share our mutual woes,\nOur mutual burdens bear,\nAnd often for each other flows\nThe sympathizing tear.\n\n4. When we are called to part,\nIt gives us inward pain;\nBut we shall still be joined in heart,\nAnd hope to meet again.\n\n5. This glorious hope revives\nOur courage by the way;\nWhile each in expectation lives\nAnd waits to see the day.\n\n6. From sorrow, toil, and pain,\nAnd sin, we shall be free;\n And perfect love and friendship reign\nThrough all eternity.",
"39. ONWARD CHRISTIAN SOLDIER":"Ee askari twende (Nyimbo za Mungu 262/209)\nBy S. Baring-Gould (1864)\n\n1. Onward, Christian soldiers,\nMarching as to war,\nWith the cross of Jesus\nGoing on before!\nChrist, the royal Master,\nLeads against the foe;\nForward into battle,\nSee his banner go!\n\nRefrain:\n\nOnward, Christian soldiers,\nMarching as to war,\nWith the cross of Jesus\nGoing on before!\n\n2. At the sign of triumph\nSatan's host doth flee;\nOn, then, Christian soldiers,\nOn to victory!\nHell's foundations quiver\nAt the shout of praise;\nBrothers, lift your voices,\nLoud your anthems raise!\n\n3. Like a mighty army\nMoves the church of God:\nBrothers, we are treading\nWhere the saints have trod;\nWe are not divided;\nAll one body we,\nOne in hope and doctrine,\nOne in charity.\n\n4. Onward, then, ye people,\nJoin our happy throng,\nBlend with ours your voices\nIn the triumph song;\nGlory, laud, and honor,\nUnto Christ the King:\nThis thro' countless ages\nMen and angels sing.",
"40. AMIDST US OUR BELOVED STANDS":"By C. H. Spurgeon (1866)\n\n1. Amidst us our Beloved stands,\nAnd bids us view His pierced hands;\nPoints to the wounded feet and side,\nBlest emblems of the Crucified.\n\n2. What food luxurious loads the board,\nWhen, at His table, sits the Lord!\nThe cup how rich, the bread how sweet,\nWhen Jesus deigns the guests to meet!\n\n3. If now, with eyes defiled and dim,\nWe see the signs, but see not Him;\nO may His love the scales displace,\nAnd bid us see Him face to face!\n\n4. Our former transports we recount,\nWhen with Him in the holy mount:\nThese cause our souls to thirst anew\nHis marred but lovely face to view.",
"41. WONDEFUL WORDS OF LIFE":"Imba neno la Mungu tena (Nyimbo za Mungu 143/90)\n By P. P. Bliss (1874)\n\n1. Sing them over again to me,\nWonderful words of life;\nlet me more of their beauty see,\nwonderful words of life;\nwords of life and beauty,\nteach me faith and duty:\n\nRefrain.:\n\nBeautiful words, wonderful words,\nwonderful words of life;\nBeautiful words, wondeful words,\nwonderful words of life.\n\n2. Christ, the blessed One, gives to all\nwonderful words of life;\nsinner, list to the laving call,\nwonderful words of life;\nall so freely given,\nwooing us to heaven:\n\n3. Sweetly echo the gospel call,\nwonderful words of life;\noffer pardon and peace to all,\nwonderful words of life;\nJesus, only Savior,sanctify forever.",
"42. THERE IS A FOUNTAIN":"Kisima chenye damu safi (Nyimbo za Mungu 168/115)\nBy William Cowper (1772)\n\n1. There is a fountain filled with blood\nDrawn from Immanuel's veins;\nAnd sinners, plunged beneath that flood,\nLose all their guilty stains:\nLose all their guilty stains,\nLose all their guilty stains;\nAnd sinners, plunged beneath that flood,\nLose all their guilty stains.\n\n2. The dying thief rejoiced to see\nThat fountain in his day;\nAnd there may I, though vile as he,\nWash all my sins away:\nWash all my sins away,\nWash all my sins away;\nAnd there may I, though vile as he,\nWash all my sins away.\n\n3. Dear dying Lamb, Thy precious blood\nShall never lose its pow'r,\nTill all the ransomed Church of God\nBe saved, to sin no more:\nBe saved, to sin no more,\nBe saved, to sin no more;\nTill all the ransomed Church of God\nBe saved to sin no more.\n\n4. E'er since by faith I saw the stream\nThy flowing wounds supply,\nRedeeming love has been my theme,\nAnd shall be till I die:\nAnd shall be till I die,\nAnd shall be till I die;\nRedeeming love has been my theme,\nAnd shall be till I die.\n\n5. When this poor lisping, stamm'ring tongue\nLies silent in the grave,\nThen in a nobler, sweeter song\nI'll sing Thy pow'r to save:\nI'll sing Thy pow'r to save,\nI'll sing Thy pow'r to save;\nThen in a nobler, sweeter song\nI'll sing Thy pow'r to save.",
"43. GRACE GREATER THAN OUR SIN": "Neema Ya Bwana ni Kubwa (Nyimbo za Mungu 139/86)\nBy Julia H. Johnston (1911)\n\n 1. Marvelous grace of our loving Lord,\nGrace that exceeds our sin and our guilt,\nYonder on Calvary's mount out-poured,\n There where the blood of the Lamb was spilt.\n\n Refrain:\n\n Grace, grace, God's grace,\nGrace that will pardon and cleanse within;\nGrace, grace, God's grace,\n Grace that is greater than all our sin.\n\n 2. Dark is the stain that we cannot hide,\n What can avail to wash it away!\n Look! there is flowing a crimson tide;\n Whiter than snow you may be today.\n\n 3. Marvelous, infinite, matchless grace\nFreely bestowed on all who believe;\nYou that are longing to see his face,\nWill you this moment his grace receive?",
"44. COME EVERY SOUL BY SIN OPPRESSED": "Ee kuja mutu wa makosa (Nyimbo za Mungu 184/131)\n By John H. Stockton (1874)\n\n1. Come, every soul by sin oppressed,\nThere's mercy with the Lord,\nAnd He will surely give you rest\nBy trusting in His word.\n\nRefrain:\n\nOnly trust Him, only trust Him,\nOnly trust Him now;\nHe will save you, He will save you,\nHe will save you now.\n\n2. For Jesus shed His precious blood\nRich blessings to bestow;\nPlunge now into the crimson flood\nThat washes white as snow.\n\n3. Yes, Jesus is the truth, the way,\nThat leads you into rest;\nBelieve in Him without delay,\nAnd you are fully blest.\n\n4. Come, then, and join this holy band,\nAnd on to glory go,\nTo dwell in that celestial land\nWhere joys immortal flow.",
"45. LOOK TO THE LAMB OF GOD": "Utafurahi kua na uhuru (Nyimbo za Mungu 133)\nBy H. G. Jackson\n\n1. If you from sin are longing to be free,\nLook to the Lamb of God;\nHe, to redeem you, died on Calvary,\nLook to the Lamb of God.\n\nChorus:\n\nLook to the Lamb of God,\nLook to the Lamb of God,\nFor He alone is able to save you\nLook to the Lamb of God.\n\n2. When Satan tempts and doubts and fears assail,\nLook to the Lamb of God;\nYou in His strength shall over all prevail,\nLook to the Lamb of God.\n\n3. Are you aweary, does the way seem long?\nLook to the Lamb of God:\nHis love will cheer and fill your heart with song,\nLook to the Lamb of God.\n\n4. Fear not when shadows on your pathway fall,\nLook to the Lamb of God;\nIn joy or sorrow Christ is all in all,\nLook to the Lamb of God.",
"46. I HAVE A SONG I LOVE TO SING": "Napenda Kumuimbia Bwana Sifa (Nyimbo Za Mungu 19)\nBy E. O. Excell\n\n1. I have a song I love to sing,\nSince I have been redeemed,\nOf my Redeemer, Savior, King,\nSince I have been redeemed.\n\nChorus:\n\nSince I have been redeemed,\nSince I have been redeemed,\nI will glory in His name;\nSince I have been redeemed,\nI will glory in my Savior's name.\n\n2. I have a Christ who satisfies,\nSince I have been redeemed,\nTo do His will my highest prize,\nSince I have been redeemed.\n\n3. I have a witness bright and clear,\nSince I have been redeemed,\nDispelling every doubt and fear,\nSince I have been redeemed.\n\n4. I have a home prepared for me,\nSince I have been redeemed,\nWhere I shall dwell eternally,\nSince I have been redeemed.",
"47. YEARS I SPENT IN VANITY AND PRIDE": "Siku nyingi nilifanya zambi (Nyimbo za Mungu 152/99)\nBy William R. Newell (1895)\n\n1. Years I spent in vanity and pride,\ncaring not my Lord was crucified,\nknowing not it was for me He died on Calvary.\n\nRefrain:\n\nMercy there was great, and grace was free;\npardon there was multiplied to me;\nthere my burdened soul found liberty at Calvary.\n\n2. By God's Word at last my sin I learned;\nthen I trembled at the law I'd spurned,\ntill my guilty soul imploring turned to Calvary.\n\n3. Now I've given to Jesus everything,\nnow I gladly own Him as my King,\nnow my raptured soul can only sing of Calvary.\n\n4. Oh, the love that drew salvation's plan!\noh, the grace that brought it down to man!\nOh, the mighty gulf that God did span at Calvary.",
"48. I LOVE TO TELL THE STORY": "Napenda Kutangaza (Nyimbo za Mungu 252/199)\nBy Kate Hankey (1866) and William G. Fischer (1869)\n\n1. I love to tell the story \nof of unseen things above,\n of Jesus and his glory,\n of Jesus and his love.\n I love to tell the story,\nbecause I know 'tis true;\n it satisfies my longings\n as nothing else can do.\n\nRefrain:\n\n I love to tell the story,\n twill be my theme in glory,\nto tell the old, old story\nof Jesus and his love.\n\n2. I love to tell the story;\n'tis pleasant to repeat\nwhat seems, each time I tell it,\nmore wonderfully sweet.\nI love to tell the story,\nfor some have never heard\nthe message of salvation\nfrom God's own Holy Word.\n\n3. I love to tell the story,\nfor those who know it best\nseem hungering and thirsting\nto hear it, like the rest.\nAnd when in scenes of glory\nI sing the new, new song,\n'twill be the old, old story\nthat I have loved so long.",
"49. WHAT CAN WASH AWAY MY SIN": "Nini ita nisafisha (Nyimbo za Mungu 166/113)\nBy Robert Lowry (1876)\n\n1. What can wash away my sin?\nNothing but the blood of Jesus.\nWhat can make me whole again?\nNothing but the blood of Jesus.\n\nRefrain:\nO precious is the flow\nthat makes me white as snow;\nno other fount I know;\nnothing but the blood of Jesus.\n\n2. For my pardon this I see:\nnothing but the blood of Jesus.\nFor my cleansing this my plea:\nnothing but the blood of Jesus.\n\n3. Nothing can for sin atone:\nnothing but the blood of Jesus.\nNaught of good that I have done:\nnothing but the blood of Jesus.\n\n4. This is all my hope and peace:\nnothing but the blood of Jesus.\nThis is all my righteousness:\nnothing but the blood of Jesus.",
"50. I HAVE REACHED THE LAND": "Ninatazama mbingu mbali (Nyimbo za Mungu 324/269)\nBy Edgar Page Stites (1876)\n\n1. I've reached the land of corn and wine.\nAnd all its riches freely mine:\nHere shines undimmed one blissful day.\nFor all my night has passed away.\n\nChorus:\n\nO Beulah Land, sweet Beulah Land,\nAs on thy highest mount I stand,\nI look away across the sea,\nWhere mansions are prepared for me,\nAnd view the shining glory shore,\nMy Heav'n, my home forevermore!\n\n2. My Savior comes and walks with me,\nAnd sweet communion here have we;\nHe gently leads me by His hand,\nFor this is Heaven's borderland.\n\n3. A sweet perfume upon the breeze\nIs borne from ever-vernal trees;\nAnd flow'rs that never fading grow\nWhere streams of life forever flow.\n\n4. The zephyrs seem to float to me,\nSweet sounds of Heaven's melody,\nAs angels with the white-robed throng\nJoin in the sweet redemption song.",
"51. IT IS WELL WITH MY SOUL": "Wakati salama inapojaza (Nyimbo za Mungu 243/190)\nBy Horatio Gates Spafford (1873)\n\n1. When peace like a river attendeth my way,\nwhen sorrows like sea billows roll;\nwhatever my lot, thou hast taught me to say,\nIt is well, it is well with my soul.\n\nRefrain (may be sung after final stanza only):\n\nIt is well with my soul;\nit is well, it is well with my soul.\n\n2. Though Satan should buffet, though trials should come,\nlet this blest assurance control:\nthat Christ has regarded my helpless estate,\n and has shed his own blood for my soul.\n\n 3. My sin oh, the bliss of this glorious thought!\nmy sin, not in part, but the whole,\nis nailed to the cross, and I bear it no more;\npraise the Lord, praise the Lord, O my soul!\n\n4. O Lord, haste the day when my faith shall be sight,\nthe clouds be rolled back as a scroll;\nthe trump shall resound and the Lord shall descend;\neven so, it is well with my soul.",
"52. TIS SO SWEET TO TRUST IN JESUS":"Ni kutamu sana kwangu (Nyimbo za Mungu 224/171)\nBy Louisa M. R. Stead (1882)\n\n1. Tis so sweet to trust in Jesus,\nand to take him at his word;\njust to rest upon his promise,\nand to know, \"Thus saith the Lord.\"\n\nRefrain:\n\nJesus, Jesus, how I trust him!\nHow I've proved him o'er and o'er!\nJesus, Jesus, precious Jesus!\no for grace to trust him more!\n\n2. O how sweet to trust in Jesus,\njust to trust his cleansing blood:\nand in simple faith to plunge me\nneath the healing, cleansing flood!\n\n3. Yes, 'tis sweet to trust in Jesus,\njust from sin and self to cease:\njust from Jesus simply taking\nlife and rest, and joy and peace.",
"53. ALL THE WAY MY SAVIOR LEADS ME": "Njia yote naongozwa (Nyimbo za Mungu 217/164)\nBy Fanny Crosby (1875)\n\n1. All the way my Savior leads me,\nWhat have I to ask beside?\nCan I doubt His tender mercy,\nWho through life has been my Guide?\nHeav'nly peace, divinest comfort,\nHere by faith in Him to dwell!\nFor I know, whate'er befall me,\nJesus doeth all things well;\nFor I know, whate'er befall me,\nJesus doeth all things well.\n\n2. All the way my Savior leads me,\nCheers each winding path I tread,\nGives me grace for every trial,\nFeeds me with the living Bread.\nThough my weary steps may falter\nAnd my soul athirst may be,\nGushing from the Rock before me,\nLo! A spring of joy I see;\nGushing from the Rock before me,\nLo! A spring of joy I see.\n\n3. All the way my Savior leads me,\nOh, the fullness of His love!\nPerfect rest to me is promised\nIn my Father's house above.\nWhen my spirit, clothed immortal,\nWings its flight to realms of day\nThis my song through endless ages:\nJesus led me all the way;\nThis my song through endless ages:\nJesus led me all the way.",
"54. FAITH IS THE VICTORY":"Askari wahodari (Nyimbo za Mungu 263/210)\nBy John Henry Yates\n\n1. Encamped along the hills of light,\nYe Christian soldiers, rise\nAnd press the battle ere the night\nShall veil the glowing skies.\nAgainst the foe in vales below\nLet all our strength be hurled;\nFaith is the victory, we know,\nThat overcomes the world.\n\nChorus:\n\nFaith is the victory! (Faith is the victory!)\nFaith is the victory! (Faith is the victory!)\nOh, glorious victory\nThat overcomes the world.\n\n2. His banner over us is love,\nOur sword the Word of God:\nWe tread the road the saints above\nWith shouts of triumph trod.\nBy faith they, like a whirlwind's breath,\nSwept on o'er every field;\nThe faith by which they conquered death\nIs still our shining shield.\n\n3. To him who overcomes the foe\nWhite raiment shall be giv'n:\nBefore the angels he shall know\nHis name confessed in heav'n\nThen onward from the hills of light,\nOur hearts with love aflame:\nWe'll vanquish all the hosts of night\nIn Jesus' conquering name.",
"55. CHANNELS ONLY":"Ninashukuru Bwana (Nyimbo za Mungu 282/229)\nBy Mary E. Maxwell (1900)\n\n1. How I praise Thee, precious Savior,\nThat Thy love laid hold of me;\nThou hast saved and cleansed and filled me\nThat I might Thy channel be.\n\nRefrain:\n\nChannels only, blessed Master,\nBut with all Thy wondrous pow'r\nFlowing through us, Thou canst use us\nEvery day and every hour.\n\n2. Just a channel full of blessing,\nTo the thirsty hearts around;\nTo tell out Thy full salvation\nAll Thy loving message sound.\n\n3. Emptied that Thou shouldest fill me,\nA clean vessel in Thy hand;\nWith no pow'r but as Thou givest\nGraciously with each command.\n\n4. Witnessing Thy pow'r to save me,\nSetting free from self and sin;\nThou who boughtest to possess me,\n In Thy fullness, Lord, come in.\n\n5. Jesus, fill now with Thy Spirit\nHearts that full surrender know;\nThat the streams of living water\nFrom our inner self may flow.",
"56. TAKE TIME TO BE HOLY":"Uchunge wakati kusemana na (Nyimbo za Mungu 234/181)\nBy William D. Longstaff (ca. 1882)\n\n1. Take time to be holy, speak oft with thy Lord:\nAbide in Him always, and feed on His Word.\nMake friends of God's children, help those who are weak.\nForgetting in nothing His blessing to seek.\n\n2. Take time to be holy, the world rushes on;\nSpend much time in secret, with Jesus alone.\nBy looking to Jesus, like Him thou shalt be;\nThy friends in thy conduct His likeness shall see.\n\n3. Take time to be holy, let Him be thy Guide;\nAnd run not before Him, whatever betide.\nIn joy or in sorrow, still follow the Lord,\nAnd, looking to Jesus, still trust in His Word.\n\n4. Take time to be holy, be calm in thy soul,\nEach thought and each motive beneath His control.\nThus led by His Spirit to fountains of love,\nThou soon shalt be fitted for service above.",
"57. NEARER MY GOD TO THEE":"Niwe karibu nawe (Nyimbo za Mungu 205/152)\nBy Sarah Flower Adams (1841)\n\n1. Nearer, my God, to thee, nearer to thee!\nE'en though it be a cross that raiseth me,\nstill all my song shall be,\nnearer, my God, to thee;\nnearer, my God, to thee, nearer to thee!\n\n2. Though like the wanderer, the sun gone down,\ndarkness be over me, my rest a stone;\nyet in my dreams I'd be\nnearer, my God, to thee;\nnearer, my God, to thee, nearer to thee!\n\n3. There let the way appear, steps unto heaven;\nall that thou sendest me, in mercy given;\nangels to beckon me\nnearer, my God, to thee;\nnearer, my God, to thee, nearer to thee!\n\n4. Then, with my waking thoughts bright with thy praise,\nout of my stony griefs Bethel I'll raise;\nso by my woes to be\nnearer, my God, to thee;\nnearer, my God, to thee, nearer to thee!\n\n5. Or if, on joyful wing cleaving the sky,\nsun, moon, and stars forgot, upward I fly,\nstill all my song shall be,\nnearer, my God, to thee;\nnearer, my God, to thee, nearer to thee!",
"58. MORE ABOUT JESUS":"Ee ninataka kusikia (nyimbo za Mungu 233/180)\nBy Eliza E. Hewitt (1887)\n\n1. More about Jesus would I know,\nMore of His grace to others show;\nMore of His saving fullness see,\nMore of His love who died for me.\n\nRefrain:\n\nMore, more about Jesus,\nMore, more about Jesus;\nMore of His saving fullness see,\nMore of His love who died for me.\n\n2. More about Jesus let me learn,\nMore of His holy will discern;\nSpirit of God, my teacher be,\nShowing the things of Christ to me.\n\n3. More about Jesus in His Word,\nHolding communion with my Lord;\nHearing His voice in ev'ry line,\nMaking each faithful saying mine.\n\n4. More about Jesus on His throne,\nRiches in glory all His own;\nMore of His kingdom's sure increase;\nMore of His coming, Prince of Peace.",
"59. TAKE MY LIFE AND LET IT BE":"Bwana upokee maisha yangu (Nyimbo za Mungu 278/225)\nBy Frances Ridley Havergal (1874)\n\n1. Take my life and let it be\nconsecrated, Lord, to thee.\nTake my moments and my days;\nlet them flow in endless praise,\nlet them flow in endless praise.\n\n2. Take my hands and let them move\nat the impulse of thy love.\nTake my feet and let them be\nswift and beautiful for thee,\nswift and beautiful for thee.\n\n3. Take my voice and let me sing\nalways, only, for my King.\nTake my lips and let them be\nfilled with messages from thee,\nfilled with messages from thee.\n\n4. Take my silver and my gold;\nnot a mite would I withhold.\nTake my intellect and use\nevery power as thou shalt choose,\nevery power as thou shalt choose.\n\n5. Take my will and make it thine;\nit shall be no longer mine.\nTake my heart it is thine own:\nit shall be thy royal throne,\nit shall be thy royal throne.\n\n6. Take my love; my Lord, I pour\nat thy feet its treasure store.\nTake myself, and I will be\never, only, all for thee,\n ever, only, all for thee.",
"60. MY JESUS I LOVE THEE":"Ee ninakupenda (Nyimbo za Mungu 375/319)\nBy William R. Featherston\n\n1. My Jesus I love Thee, I know Thou art mine\nFor Thee all the follies of sin I resign\nMy gracious Redeemer, my Saviour art Thou\nIf ever I loved Thee my Jesus 'tis now\n\n2. I love Thee because Thou has first loved me\nAnd purchased my pardon on Calvary's tree\nI love Thee for wearing the thorns on Thy brow\nIf ever I loved Thee my Jesus 'tis now\n\n3. I'll love Thee in life and I will love Thee in death\nAnd praise Thee as long as Thou lendest me breath\nAnd say when the death dew lies cold on my brow\nIf ever I loved Thee my Jesus 'tis now\n\n4. In mansions of glory and endless delight\nI'll ever adore Thee in heaven so bright\nI'll sing with the glittering crown on my brow\nIf ever I loved Thee my Jesus 'tis now\n",
"61. ALL FOR JESUS":"Yote kwa mwokozi wangu (Nyimbo za Mungu 375/319)\nBy Mary D. James\n\n1. All for Jesus! all for Jesus!\nAll my being's ransom'd pow'rs;\nAll my thoughts and words and doings,\nAll my days and all my hours.\nAll for Jesus! all for Jesus!\nAll my days and all my hours.\n\n2. Let my hands perform his bidding;\nLet my feet run in his ways;\nLet my eyes see Jesus only;\nLet my lips speak forth his praise.\nAll for Jesus! all for Jesus!\nLet my lips speak forth his praise.\n\n3. Worldlings prize their gems of beauty,\nCling to gilded toys of dust,\nBoast of wealth, and fame, and pleasure;\nOnly Jesus will I trust.\nOnly Jesus! only Jesus!\nOnly Jesus will I trust.\n\n4. Since my eyes were fixed on Jesus,\nI've lost sight of all beside,--\nSo enchained my spirit's vision,\nLooking at the crucified.\nAll for Jesus! all for Jesus!\nAll for Jesus, crucified!\n\n5. Oh, what wonder! how amazing!\nJesus, glorious King of kings,\nDeigns to call me his beloved.\nLets me rest beneath his wings.\nAll for Jesus! all for Jesus!\nResting now beneath his wings.",
"62. REVIVE US AGAIN":"Heshima na sifa (Nyimbo za Mungu 2)\nBy W. P. Mackay (1863, 1867)\n\n1. We praise thee, O God, for the Son of thy love,\nFor Jesus who died and is now gone above.\n\nRefrain:\n\nHallelujah, thine the glory!\nHallelujah, Amen!\nHallelujah, thine the glory!\nRevive us again.\n\n2. We praise thee, O God, for thy Spirit of light,\nWho has shown us our Savior and scattered our night.\n\n3. All glory and praise to the Lamb that was slain,\nWho has borne all our sins and has cleansed ev'ry stain.\n\n4. Revive us again - fill each heart with thy love;\nMay each soul be rekindled with fire from above.",
"63. I AM PRESSING ON THE UPWARD WAY":"Unitembeze Bwana wangu (Nyimbo za Mungu 235/182)\nBy Johnson Oatman, Jr.\n\n1. I'm pressing on the upward way,\nNew heights I'm gaining every day;\nStill praying as I'm onward bound,\n\"Lord, plant my feet on higher ground.\"\n\nRefrain:\n\nLord, lift me up and let me stand,\nBy faith, on Heaven's tableland,\nA higher plane than I have found;\nLord, plant my feet on higher ground.\n\n2. My heart has no desire to stay\nWhere doubts arise and fears dismay;\nThough some may dwell where those abound,\nMy prayer, my aim, is higher ground.\n\n3. I want to live above the world,\nThough Satan's darts at me are hurled;\nFor faith has caught the joyful sound,\nThe song of saints on higher ground.\n\n4. I want to scale the utmost height\nAnd catch a gleam of glory bright;\nBut still I'll pray till heav'n I've found,\n\"Lord, plant my feet on higher ground.\" ",
"64. THERE IS A PLACE OF QUIET REST":"Pahali pa salama tamu (Nyimbo za Mungu 287/234)\nBy Cleland Boyd McAfee (1903)\n\n1. There is a place of quiet rest,\nnear to the heart of God,\na place where sin cannot molest,\nnear to the heart of God.\n\nRefrain:\n\nO Jesus, blest Redeemer,\nsent from the heart of God,\nhold us, who wait before thee,\nnear to the heart of God.\n\n2. There is a place of comfort sweet,\nnear to the heart of God,\na place where we our Savior meet,\nnear to the heart of God.\n\n3. There is a place of full release,\nnear to the heart of God,\na place where all is joy and peace,\nnear to the heart of God.",
"65. WHAT A FELLOWSHIP, WHAT A JOY DIVINE":"Nina ushirika (Nyimbo za Mungu 210/157)\nBy E. A. Hoffman (1887)\n\n1. What a fellowship, what a joy divine,\nleaning on the everlasting arms;\nwhat a blessedness, what a peace is mine,\nleaning on the everlasting arms.\n\nRefrain:\n\nLeaning, leaning,\nsafe and secure from all alarms;\nleaning, leaning,\nleaning on the everlasting arms.\n\n2. O how sweet to walk in this pilgrim way,\nleaning on the everlasting arms;\nO how bright the path grows from day to day,\nleaning on the everlasting arms.\n\n3. What have I to dread, what have I to fear,\nleaning on the everlasting arms?\nI have blessed peace with my Lord so near,\nleaning on the everlasting arms.",
"66. THE GREAT PHYSICIAN":"Muganga amekuja hapa (Nyimbo za Mungu 155/102)\nBy William Hunter\n\n1. The great Physician now is near,\nthe sympathizing Jesus;\nHe speaks the drooping heart to cheer,\noh! hear the voice of Jesus.\n\nRefrain:\n\nSweetest note in seraph song,\nSweetest name on mortal tongue;\nSweetest carol ever Sung,\nJesus, blessed Jesus.\n\n2. Your many sins are all forgiven,\nOh! hear the voice of Jesus;\ngo on your way in peace to heaven,\nand wear a crown with Jesus.\n\n3. All glory to the risen Lamb!\nI now believe in Jesus;\nI love the blessed Savior's name,\nI love the name of Jesus.\n\n4. His name dispels my guilt and fear,\nno other name but Jesus;\noh! how my soul delights to hear\nthe charming name of Jesus.",
"67. WONDERFUL PEACE":"Nimepata salama (Nyimbo za Mungu 371/315)\nBy W. D. Cornell (19th Century)\n\n1. Far away in the depths of my spirit tonight\nRolls a melody sweeter than psalm;\nIn celestial-like strains it unceasingly falls\nO'er my soul like an infinite calm.\n\nRefrain:\nPeace! peace! wonderful peace,\nComing down from the Father above:\nSweep over my spirit forever, I pray,\nIn fathomless billows of love.\nWhat a treasure I have in this Wonderful peace,\n\n2. Buried deep in the heart of my soul;\nSo secure that no power can mine it away,\nWhile the years of eternity roll.\n\n3. I am resting tonight in this wonderful peace,\nResting sweetly in Jesus' control;\nFor I'm kept from all danger by night and by day,\nAnd His glory is flooding my soul.\n\n4. And I know when I rise to that city of peace,\nWhere the Author of peace I shall see,\nThat one strain of the anthems the ransomed will sing,\nIn that heavenly kingdom shall be:\n\n5. O soul, are you here without comfort or rest,\nWalking down the rough pathway of time?\nMake Jesus your friend ere the shadows grow dark;\nO accept this sweet peace so sublime.",
"68. JUST AS I AM":"Tel que Je suis, Na hali yangu (Nyimbo za Mungu 179/126)\nBy Charlotte Elliott\n\n1. Just as I am, without one plea,\nbut that thy blood was shed for me,\nand that thou bidd'st me come to thee,\nO Lamb of God, I come, I come.\n\n2. Just as I am, and waiting not\nto rid my soul of one dark blot,\nto thee, whose blood can cleanse each spot,\nO Lamb of God, I come, I come.\n\n3. Just as I am, though tossed about\nwith many a conflict, many a doubt,\nfightings and fears within, without,\nO Lamb of God, I come, I come.\n\n4. Just as I am, thou wilt receive,\nwilt welcome, pardon, cleanse, relieve;\nbecause thy promise I believe,\nO Lamb of God, I come, I come.",
"69. HOW GREAT THOU ART":"Nina fikili Mungu Baba (Nyimbo za Mungu 11)\nBy Carl Gustav Boberg\n\n1. Lord my God when I in awesome wonder\nConsider all the works Thy hands have made,\nI see the stars, I hear the rolling thunder,\nThy power throughout the universe displayed.\n\nRefrain:\n\nThen sings my soul, my Savior God, to thee:\nHow great Thou art, how great Thou art!\n\n2. When through the woods and forest glades I wander,\nAnd hear the birds sing sweetly in the trees;\nWhen I look down from lofty mountain grandeur,\nAnd hear the brook, and feel the gentle breeze:\n\n3. And when I think that God, His Son not sparing,\nSent Him to die, I scarce can take it in;\nThat on the cross, my burden gladly bearing,\nHe bled and died to take away my sin.\n\n4. When Christ shall come with shout of acclamation\nAnd take me home, what joy shall fill my heart!\nThen I shall bow in humble adoration\nAnd there proclaim, my God, how great Thou art!",
"70. STAND UP FOR JESUS":"Simama kwa mufalme (Nyimbo za Mungu 256/203)\nBy George Duffield (1858)\n\n1. Stand up, stand up for Jesus,\nye soldiers of the cross!\nLift high his royal banner,\nit must not suffer loss.\nFrom victory unto victory\nhis army he shall lead,\ntill every foe is vanquished,\nand Christ is Lord indeed.\n\n2. Stand up, stand up for Jesus,\nthe solemn watchword hear:\nif while ye sleep he suffers,\naway with shame and fear.\nWhere'er ye meet with evil,\nwithin you or without,\ncharge for the God of battles,\nand put the foe to rout.\n\n3. Stand up, stand up for Jesus,\nstand in his strength alone;\nthe arm of flesh will fail you,\nye dare not trust your own.\nPut on the gospel armour,\neach piece put on with prayer;\nwhen duty calls or danger\nbe never wanting there.\n\n4. Stand up, stand up for Jesus,\nthe strife will not be long\nthis day the noise of battle,\nthe next the victor's song.\nTo him that overcometh\na crown of life shall be;\nhe with the King of glory shall reign eternally.",
"71. JESUS SAVES":"Tumepata neno nzuri (Nyimbo za Mungu 119)\nBy Priscilla J. Owens\n\n1. We have heard the joyful sound:\nJesus saves!\nSpread the gladness all around:\nJesus saves!\nBear the news to every land,\nclimb the steeps and cross the waves;\nonward! 'tis our Lord's command:\nJesus saves!\n\n2. Sing above the battle strife:\nJesus saves!\nBy His death and endless life, Jesus saves!\n Sing it softly through the gloom,\n when the heart for mercy craves;\nsing in triumph o'er the tomb:\nJesus saves!\n\n3. Give the winds a mighty voice: Jesus saves!\nLet the nations now rejoice:Jesus saves!\nShout salvation full and free;\nhighest hills and deepest caves;\nthis our song of victory:Jesus saves!",
"72. DOWN IN THE VALLEY WITH MY SAVIOR":"Ninataaka kumufata Yesu Mwok. (Nyimbo za Mungu 179)\nBy W. O. Cushing (1878)\n1. Down in the valley with my Savior I would go,\nWhere the flowers are blooming and the sweet waters flow;\nEverywhere He leads me I will follow, follow on,\nWalking in His footsteps till the crown be won.\n\nChorus:\n\nFollow! follow! I will follow Jesus!\nAnywhere, everywhere, I will follow on!\nFollow! follow! I will follow Jesus!\nEverywhere He leads me I will follow on!\n\n2. Down in the valley with my Savior I would go,\nWhere the storms are sweeping and the dark waters flow;\nWith His hand to lead me I will never, never fear,\nDanger cannot fright me if my Lord is near.\n\n3. Down in the valley or upon the mountain steep,\nClose beside my Savior would my soul ever keep;\nHe will lead me safely in the path that He has trod,\nUp to where they gather on the hills of God.",
"73. THE SOLID ROCK":"Ninasimama kwake Kristo (Nyimbo za Mungu 195)\nBy Edward Mote (1834)\n\n1. My hope is built on nothing less\nthan Jesus' blood and righteousness;\nI dare not trust the sweetest frame,\nbut wholly lean on Jesus' name.\nOn Christ, the solid Rock, I stand;\nall other ground is sinking sand.\n\n2. When darkness veils His lovely face,\nI rest on His unchanging grace;\nin ev'ry high and stormy gale\nmy anchor holds within the veil.\nOn Christ, the solid Rock, I stand;\nall other ground is sinking sand.\n\n3. His oath, His covenant, His blood\n support me in the 'whelming flood;\nwhen all around my soul gives way\nHe then is all my hope and stay.\nOn Christ, the solid Rock, I stand;\nall other ground is sinking sand.\n\n4. When He shall come with trumpet sound,\nO may I then in Him be found,\ndressed in His righteousness alone,\nfaultless to stand before the throne.\nOn Christ, the solid Rock, I stand;\nall other ground is sinking sand.",

};

function populateHymnSelector() {
    const hymnSelector = document.getElementById("hymnSelector");
    Object.keys(hymnsData).forEach(hymn => {
        const option = document.createElement("option");
        option.value = hymn;
        option.textContent = hymn;
        hymnSelector.appendChild(option);
    });
}

const urlParams = new URLSearchParams(window.location.search);
const currentTitle = urlParams.get('title');

function getAdjacentHymn(direction) {
    const titles = Object.keys(hymnsData);
    const currentIndex = titles.indexOf(currentTitle);

    if (direction === 'next' && currentIndex < titles.length - 1) {
        return titles[currentIndex + 1];
    } else if (direction === 'previous' && currentIndex > 0) {
        return titles[currentIndex - 1];
    }
    return null;
}

let touchStartX = 0;
let touchEndX = 0;

document.addEventListener('touchstart', (e) => {
    touchStartX = e.touches[0].clientX;
});

document.addEventListener('touchend', (e) => {
    touchEndX = e.changedTouches[0].clientX;
    handleSwipe();
});

function handleSwipe() {
    const swipeDistance = touchStartX - touchEndX;
    if (swipeDistance > 100) {
        const nextHymn = getAdjacentHymn('next');
        if (nextHymn) {
            window.location.href = `lyrics.html?title=${encodeURIComponent(nextHymn)}`;
        }
    } else if (swipeDistance < -100) {
        const previousHymn = getAdjacentHymn('previous');
        if (previousHymn) {
            window.location.href = `lyrics.html?title=${encodeURIComponent(previousHymn)}`;
        }
    }
}

document.querySelectorAll('.hymn').forEach(button => {
    button.addEventListener('click', () => {
        const hymnTitle = button.getAttribute('data-title');
        window.location.href = `lyrics.html?title=${encodeURIComponent(hymnTitle)}`;
    });
});

document.getElementById('search-button').addEventListener('click', performSearch);
document.getElementById('song-search').addEventListener('keydown', function (event) {
    if (event.key === 'Enter') {
        performSearch();
    }
});
document.getElementById('song-search').addEventListener('input', performSearch);

function performSearch() {
    const searchTerm = document.getElementById('song-search').value.toLowerCase();
    const matchedHymns = Object.keys(hymnsData).filter(title =>
        title.toLowerCase().includes(searchTerm) ||
        (hymnsData[title] && hymnsData[title].toLowerCase().includes(searchTerm))
    );

    const lyricsDiv = document.getElementById('lyrics');

    if (matchedHymns.length > 0) {
        const hymnList = matchedHymns.map(hymn =>
            `<button class="hymn" data-title="${hymn}">${hymn}</button>`
        ).join('');
        lyricsDiv.innerHTML = `<h5>Matching Hymns:</h5><div class="hymn-button">${hymnList}</div>`;
        lyricsDiv.hidden = false;

        matchedHymns.forEach(hymn => {
            const button = document.querySelector(`.hymn[data-title="${CSS.escape(hymn)}"]`);
            button.addEventListener('click', () => {
                window.location.href = `lyrics.html?title=${encodeURIComponent(hymn)}`;
            });
        });
    } else {
        lyricsDiv.innerHTML = 'No matching hymns found.';
        lyricsDiv.hidden = false;
    }
}

function changeTheme() {
    const themeBtn = document.getElementById('theme');
    themeBtn.innerHTML = themeBtn.innerHTML === '🌙' ? '☀' : '🌙';
}

function applyTheme() {
    const theme = localStorage.getItem('theme');
    if (theme) {
        document.body.className = theme;
    }
}

function toggleTheme() {
    let currentTheme = document.body.className;
    let newTheme = currentTheme === 'dark' ? 'light' : 'dark';
    document.body.className = newTheme;
    localStorage.setItem('theme', newTheme);
}

document.getElementById('back-button').addEventListener('click', () => {
    window.history.back();
});

function goToNextSong() {
    const nextHymn = getAdjacentHymn('next');
    if (nextHymn) {
        window.location.href = `lyrics.html?title=${encodeURIComponent(nextHymn)}`;
    }
}

function goToPreviousSong() {
    const previousHymn = getAdjacentHymn('previous');
    if (previousHymn) {
        window.location.href = `lyrics.html?title=${encodeURIComponent(previousHymn)}`;
    }
}